---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spark-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 42G
  storageClassName: manila-cephfs-share

