---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spark-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
  storageClassName: csi-manila-cephfs