apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: manila-cephfs-share
provisioner: manila-provisioner
parameters:
  type: cephfsnativetype
  zones: nova
  osSecretName: my-manila-secrets
  osSecretNamespace: default

  protocol: CEPHFS
  backend: cephfs
